### ISSUE TITLE
Not working in 0.42.0

### ISSUE THREAD

**Issue by obmutescences** [dawsers/hyprscroller#39]
hyprland version:

Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

error:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/zerone && PKG_CONFIG_PATH="/home/zerone/.local/share/hyprpm/headersRoot/share/pkgconfig" make release
cmake -B ./Release -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=
-- The CXX compiler identification is GNU 14.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Checking for module 'hyprland'
--   Found hyprland, version 0.42.0
-- Checking for modules 'hyprutils;hyprlang;pixman-1;libdrm'
--   Found hyprutils, version 0.2.1
--   Found hyprlang, version 0.5.2
--   Found pixman-1, version 0.43.4
--   Found libdrm, version 2.4.122
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/zerone/Release
cmake --build ./Release -j
make[1]: Entering directory '/tmp/hyprpm/zerone/Release'
[ 25%] Building CXX object CMakeFiles/hyprscroller.dir/src/main.cpp.o
[ 50%] Building CXX object CMakeFiles/hyprscroller.dir/src/dispatchers.cpp.o
[ 75%] Building CXX object CMakeFiles/hyprscroller.dir/src/scroller.cpp.o
In file included from /usr/include/c++/14.2.1/bits/shared_ptr_base.h:59,
                 from /usr/include/c++/14.2.1/bits/shared_ptr.h:53,
                 from /usr/include/c++/14.2.1/chrono:49,
                 from /home/zerone/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../debug/Log.hpp:6,
                 from /home/zerone/.local/share/hyprpm/headersRoot/include/hyprland/src/config/ConfigManager.hpp:6,
                 from /tmp/hyprpm/zerone/src/main.cpp:1:
/usr/include/c++/14.2.1/bits/unique_ptr.h: In instantiation of ‘constexpr std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...) [with _Tp = ScrollerLayout; _Args = {}; __detail::__unique_ptr_t<_Tp> = __detail::__unique_ptr_t<ScrollerLayout>]’:
/tmp/hyprpm/zerone/src/main.cpp:21:56:   required from here
   21 |     g_ScrollerLayout = std::make_unique<ScrollerLayout>();
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/c++/14.2.1/bits/unique_ptr.h:1076:30: error: invalid new-expression of abstract class type ‘ScrollerLayout’
 1076 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/hyprpm/zerone/src/main.cpp:6:
/tmp/hyprpm/zerone/src/scroller.h:11:7: note:   because the following virtual functions are pure within ‘ScrollerLayout’:
   11 | class ScrollerLayout : public IHyprLayout {
      |       ^~~~~~~~~~~~~~
In file included from /tmp/hyprpm/zerone/src/scroller.h:1:
/home/zerone/.local/share/hyprpm/headersRoot/include/hyprland/src/layout/IHyprLayout.hpp:113:18: note:     ‘virtual void IHyprLayout::fullscreenRequestForWindow(PHLWINDOW, eFullscreenMode, eFullscreenMode)’
  113 |     virtual void fullscreenRequestForWindow(PHLWINDOW pWindow, const eFullscreenMode CURRENT_EFFECTIVE_MODE, const eFullscreenMode EFFECTIVE_MODE) = 0;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/hyprpm/zerone/src/scroller.cpp: In member function ‘bool Column::toggle_fullscreen(const Box&)’:
/tmp/hyprpm/zerone/src/scroller.cpp:347:18: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
  347 |         wactive->m_bIsFullscreen = !wactive->m_bIsFullscreen;
      |                  ^~~~~~~~~~~~~~~
      |                  isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp:347:46: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
  347 |         wactive->m_bIsFullscreen = !wactive->m_bIsFullscreen;
      |                                              ^~~~~~~~~~~~~~~
      |                                              isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp:348:22: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
  348 |         if (wactive->m_bIsFullscreen) {
      |                      ^~~~~~~~~~~~~~~
      |                      isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp:351:25: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
  351 |         return wactive->m_bIsFullscreen;
      |                         ^~~~~~~~~~~~~~~
      |                         isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp: In member function ‘bool Column::fullscreen() const’:
/tmp/hyprpm/zerone/src/scroller.cpp:385:46: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
  385 |         return active->data()->ptr().lock()->m_bIsFullscreen;
      |                                              ^~~~~~~~~~~~~~~
      |                                              isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp: In member function ‘void Row::toggle_fullscreen_active_window()’:
/tmp/hyprpm/zerone/src/scroller.cpp:1213:63: error: ‘FULLSCREEN_FULL’ is not a member of ‘eFullscreenMode’
 1213 |             PWORKSPACE->m_efFullscreenMode = eFullscreenMode::FULLSCREEN_FULL;
      |                                                               ^~~~~~~~~~~~~~~
/tmp/hyprpm/zerone/src/scroller.cpp: In member function ‘virtual void ScrollerLayout::recalculateMonitor(const int&)’:
/tmp/hyprpm/zerone/src/scroller.cpp:1598:81: error: ‘FULLSCREEN_FULL’ was not declared in this scope
 1598 |     if (PWORKSPACE->m_bHasFullscreenWindow && PWORKSPACE->m_efFullscreenMode == FULLSCREEN_FULL) {
      |                                                                                 ^~~~~~~~~~~~~~~
/tmp/hyprpm/zerone/src/scroller.cpp: In member function ‘virtual void ScrollerLayout::fullscreenRequestForWindow(PHLWINDOW, eFullscreenMode, bool)’:
/tmp/hyprpm/zerone/src/scroller.cpp:1662:27: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
 1662 |         if (on == window->m_bIsFullscreen)
      |                           ^~~~~~~~~~~~~~~
      |                           isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp:1683:17: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
 1683 |         window->m_bIsFullscreen = on;
      |                 ^~~~~~~~~~~~~~~
      |                 isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp:1692:22: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
 1692 |         if (!window->m_bIsFullscreen) {
      |                      ^~~~~~~~~~~~~~~
      |                      isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp:1697:21: error: ‘class CWindow’ has no member named ‘updateSpecialRenderData’
 1697 |             window->updateSpecialRenderData();
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/hyprpm/zerone/src/scroller.cpp:1704:35: error: ‘FULLSCREEN_FULL’ was not declared in this scope
 1704 |             if (fullscreenmode == FULLSCREEN_FULL) {
      |                                   ^~~~~~~~~~~~~~~
/tmp/hyprpm/zerone/src/scroller.cpp:1721:31: error: ‘FULLSCREEN_FULL’ is not a member of ‘eFullscreenMode’
 1721 |         case eFullscreenMode::FULLSCREEN_FULL:
      |                               ^~~~~~~~~~~~~~~
/tmp/hyprpm/zerone/src/scroller.cpp:1722:31: error: ‘class CWindow’ has no member named ‘m_bIsFullscreen’; did you mean ‘isFullscreen’?
 1722 |             if (on == window->m_bIsFullscreen)
      |                               ^~~~~~~~~~~~~~~
      |                               isFullscreen
/tmp/hyprpm/zerone/src/scroller.cpp:1731:31: error: ‘FULLSCREEN_MAXIMIZED’ is not a member of ‘eFullscreenMode’
 1731 |         case eFullscreenMode::FULLSCREEN_MAXIMIZED:
      |                               ^~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/hyprscroller.dir/build.make:76: CMakeFiles/hyprscroller.dir/src/main.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/hyprscroller.dir/build.make:104: CMakeFiles/hyprscroller.dir/src/scroller.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hyprscroller.dir/all] Error 2
make[1]: *** [Makefile:91: all] Error 2
make[1]: Leaving directory '/tmp/hyprpm/zerone/Release'
make: *** [Makefile:13: release] Error 2

**Comment by dawsers** [comment]
I am still working on the update to 0.42. There are two changes in the API and I am still debugging. It will still take 2-3 days in case anyone wants to defer the update.

**Comment by obmutescences** [comment]
> I am still working on the update to 0.42. There are two changes in the API and I am still debugging. It will still take 2-3 days in case anyone wants to defer the update.

nice. great working.

**Comment by dawsers** [comment]
Fixed in 82b333c7548c279c11ede3878e59c9909cd64e53
